// lib/mail.js
// Central mail service for the app. Uses SendGrid — swap the transport
// section for Amazon SES later without touching call sites.

const sgMail = require('@sendgrid/mail');

const FROM_EMAIL = process.env.MAIL_FROM || 'no-reply@yourdomain.co.ke';
const FROM_NAME = process.env.MAIL_FROM_NAME || 'Receipt System';
const ADMIN_EMAIL = process.env.ADMIN_ALERT_EMAIL; // optional, for admin alerts

if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
} else {
  console.warn('[mail] SENDGRID_API_KEY not set — emails will be logged, not sent.');
}

/**
 * Low-level send. Falls back to console logging if no API key is
 * configured, so local dev never crashes on a missing key.
 */
async function send({ to, subject, html, text, attachments }) {
  if (!process.env.SENDGRID_API_KEY) {
    console.log(`[mail:dev] Would send to ${to} — "${subject}"`);
    return { devMode: true };
  }

  const msg = {
    to,
    from: { email: FROM_EMAIL, name: FROM_NAME },
    subject,
    text: text || undefined,
    html,
    attachments, // [{ content: base64string, filename, type, disposition }]
  };

  try {
    await sgMail.send(msg);
    return { sent: true };
  } catch (err) {
    console.error('[mail] Send failed:', err.response?.body || err.message);
    throw err;
  }
}

/**
 * Password reset email — replaces the "show link in browser" flow.
 */
async function sendPasswordReset({ to, resetUrl, userName }) {
  const subject = 'Reset your password';
  const html = `
    <p>Hi ${userName || 'there'},</p>
    <p>We received a request to reset your password. Click the link below to choose a new one:</p>
    <p><a href="${resetUrl}">${resetUrl}</a></p>
    <p>This link expires in 1 hour. If you didn't request this, you can ignore this email.</p>
  `;
  return send({ to, subject, html });
}

/**
 * Email a finalized receipt as a PDF attachment.
 * pdfBuffer: the Buffer already generated by lib/pdf.js
 */
async function sendReceiptEmail({ to, clientName, receiptNumber, pdfBuffer }) {
  const subject = `Your Receipt ${receiptNumber}`;
  const html = `
    <p>Hi ${clientName || 'there'},</p>
    <p>Please find attached your receipt <strong>${receiptNumber}</strong>.</p>
    <p>Thank you for your business.</p>
  `;
  return send({
    to,
    subject,
    html,
    attachments: [
      {
        content: pdfBuffer.toString('base64'),
        filename: `${receiptNumber}.pdf`,
        type: 'application/pdf',
        disposition: 'attachment',
      },
    ],
  });
}

/**
 * Low-stakes admin alerts — new user created, etc.
 * Silently no-ops if ADMIN_ALERT_EMAIL isn't set.
 */
async function sendAdminAlert({ subject, message }) {
  if (!ADMIN_EMAIL) return { skipped: true };
  return send({
    to: ADMIN_EMAIL,
    subject: `[Receipt System] ${subject}`,
    html: `<p>${message}</p>`,
  });
}

module.exports = {
  sendPasswordReset,
  sendReceiptEmail,
  sendAdminAlert,
};
